theme: jekyll-theme-cayman
title: Forging Change
description: Companion site for Forging Change by James Carpenter
google_analytics: UA-108114248-1
url: http://forgingchange.com
plugins:
  - jekyll-redirect-from

